#!/usr/bin/env node

var path = require('path');
var fs = require('fs');
var swig = require('swig');
var RSS = require('rss');
var mkdirp = require('mkdirp');

var VIEWS_DIR = "views";
var BUILD_DIR = "www";

var RSS_MAX_COUNT = 10;

mkdirp.sync(BUILD_DIR);

swig.init({
  root: VIEWS_DIR,
  allowErrors: true,
  cache: false,
});

var postList = [
  {
    filename: "zig-programming-language-blurs-line-compile-time-run-time.html",
    content: null,
    date: new Date("2017-01-30T08:19:59.949Z"),
    title: "Zig Programming Language Blurs the Line Between Compile-Time and Run-Time",
  },
  {
    filename: "troubleshooting-zig-regression-apitrace.html",
    content: null,
    date: new Date("2017-01-17T23:25:58.562Z"),
    title: "Troubleshooting a Zig Regression with apitrace",
  },
  {
    filename: "intro-to-zig.html",
    content: null,
    date: new Date("2016-02-08T16:07:35.206Z"),
    title: "Introduction to the Zig Programming Language",
  },
  {
    filename: "raspberry-pi-music-player-server.html",
    content: null,
    date: new Date("2014-06-20T00:58:08.071Z"),
    title: "Turn Your Raspberry Pi into a Music Player Server",
  },
  {
    filename: "laptop-review-bonobo-extreme.html",
    content: null,
    date: new Date("2014-06-12T23:25:14.054Z"),
    title: "Laptop Review - Bonobo Extreme",
  },
  {
    filename: "quest-build-ultimate-music-player.html",
    content: null,
    date: new Date("2014-04-22T17:39:04.442Z"),
    title: "My Quest to Build the Ultimate Music Player",
  },
  {
    filename: "do-not-use-bodyparser-with-express-js.html",
    content: null,
    date: new Date("2013-09-06T22:37:07.244Z"),
    title: 'Do Not Use bodyParser with Express.js',
  },
  {
    filename: "js-callback-organization.html",
    content: null,
    date: new Date("2013-08-17T04:41:14.188Z"),
    title: 'JavaScript Callbacks are Pretty Okay',
  },
  {
    filename: "not-a-js-developer.html",
    content: null,
    date: new Date("2013-08-14T15:29:13.996Z"),
    title: 'I am not a "JavaScript Developer".',
  },
  {
    filename: "7drts-game-reviews.html",
    content: null,
    date: new Date("2013-07-30T09:54:32.905Z"),
    title: "7dRTS Game Reviews",
  },
  {
    filename: "pillagers-7drts-game-dev-journal.html",
    content: null,
    date: new Date("2013-07-23T10:09:53.701Z"),
    title: "Pillagers! 7dRTS Game Development Journal",
  },
  {
    filename: "js-private-methods.html",
    content: null, // on init fill this with content from filename
    date: new Date("2013-07-17T02:20:54.462Z"),
    title: "Private Methods in JavaScript",
  },
  {
    filename: "spot-the-fail.html",
    content: null, // on init fill this with content from filename
    date: new Date("2013-07-10T21:47:20.875Z"),
    title: "Spot the Fail",
  },
  {
    filename: "jamulator.html",
    content: null, // on init fill this with content from filename
    date: new Date("2013-06-07T08:48:00.721Z"),
    title: "Statically Recompiling NES Games into Native Executables with LLVM and Go",
  },
  {
    filename: "swig-email-templates.html",
    content: null, // on init fill this with content from filename
    date: new Date("2013-01-30T12:00:00.000Z"),
    title: "Rapid Development Email Templates with Node.js",
  },
  {
    filename: "pyweek-success.html",
    content: null, // on init fill this with content from filename
    date: new Date("2011-08-07T12:00:00.000Z"),
    title: "How to be Successful at PyWeek",
  },
  {
    filename: "jmt.html",
    content: null, // on init fill this with content from filename
    date: new Date("2011-08-04T12:00:00.000Z"),
    title: "John Muir Trail from the Perspective of Andrew Kelley",
  },
  {
    filename: "lemming-pyweek-12.html",
    content: null, // on init fill this with content from filename
    date: new Date("2011-04-02T12:00:00.000Z"),
    title: "Lemming - PyWeek #12 Game Development Journal",
  },
];
readPostContentAndGenerateRss();

render("index.html", "home", {posts: postList});
postList.forEach(function(post) {
  render(path.join("post", post.filename), "post", {post: post});
});

function render(file, viewName, context) {
  var template = swig.compileFile(viewName + ".html");
  var html = template.render(context);
  var fullPath = path.join(BUILD_DIR, file);
  mkdirp.sync(path.dirname(fullPath));
  fs.writeFileSync(fullPath, html);
}


function readPostContentAndGenerateRss() {
  // cache the file content for each post in memory
  // also create a list of posts ordered by date
  // also create the RSS feed
  var feed = new RSS({
    title: "Andrew Kelley",
    description: "My personal website - thoughts, project demos, research.",
    feed_url: "http://andrewkelley.me/rss.xml",
    site_url: "http://andrewkelley.me/",
    image_url: "https://s3.amazonaws.com/superjoe/blog-files/profile-48x58.jpg",
    author: "Andrew Kelley",
  });
  postList.forEach(function(post, i) {
    post.content = fs.readFileSync(path.join("posts", post.filename), {encoding: 'utf8'});
    if (i < RSS_MAX_COUNT) {
      feed.item({
        title: post.title,
        description: post.content,
        url: "http://andrewkelley.me/post/" + post.filename,
        date: post.date,
      });
    }
  });
  fs.writeFileSync(path.join(BUILD_DIR, "rss.xml"), feed.xml());
}
