name: Language Proposal
description: Propose to improve the Zig language
labels: ["proposal"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in improving the Zig language. However, we are
        not accepting new proposals to change the language at this time.
        **Please do not file a proposal to change the language.**
  - type: checkboxes
    id: trash
    attributes:
      label: GitHub requires this checkbox to be here
      options:
        - label: Please don't check this box
          required: true
